### ======================
### LLM SETTINGS
### ======================
models:
  default_chat_model:
    type: chat
    model_provider: huggingface
    auth_type: api_key
    api_key: ${HUGGINGFACEHUB_API_TOKEN}
    model: huggingface/microsoft/Phi-3-mini-4k-instruct
    model_supports_json: true
    concurrent_requests: 2
    async_mode: threaded
    max_retries: 5

  default_embedding_model:
    type: embedding
    model_provider: huggingface
    auth_type: api_key
    api_key: ${HUGGINGFACEHUB_API_TOKEN}
    model: huggingface/sentence-transformers/all-MiniLM-L6-v2
    concurrent_requests: 5
    async_mode: threaded
    max_retries: 5



### ======================
### INPUT SETTINGS
### ======================

input:
  storage:
    type: file
    base_dir: "input"
  file_type: text

chunks:
  size: 1200
  overlap: 100

### ======================
### OUTPUT & STORAGE
### ======================

output:
  type: file
  base_dir: "output"

cache:
  type: file
  base_dir: "cache"

reporting:
  type: file
  base_dir: "logs"

vector_store:
  default_vector_store:
    type: lancedb
    db_uri: output/lancedb
    container_name: default

### ======================
### WORKFLOWS
### ======================

embed_text:
  model_id: default_embedding_model
  vector_store_id: default_vector_store

extract_graph:
  model_id: default_chat_model
  prompt: "prompts/extract_graph.txt"
  entity_types: [organization, person, geo, event]
  max_gleanings: 1

summarize_descriptions:
  model_id: default_chat_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english
  async_mode: threaded

cluster_graph:
  max_cluster_size: 10

extract_claims:
  enabled: false

community_reports:
  model_id: default_chat_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000

embed_graph:
  enabled: false

umap:
  enabled: false

snapshots:
  graphml: false
  embeddings: false

### ======================
### QUERY MODES
### ======================

local_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  chat_model_id: default_chat_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_search_reduce_prompt.txt"

basic_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"
